# Generated by Django 6.0.1 on 2026-04-09 05:04

import django.utils.timezone
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(db_index=True, max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=5)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=15)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('exited', 'Exited')], db_index=True, default='active', max_length=10)),
                ('qr_token', models.CharField(db_index=True, default=secrets.token_hex, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parking_bookings',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parking_fines',
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('slot_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=5)),
                ('is_occupied', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parking_slots',
                'ordering': ['slot_id'],
            },
        ),
    ]
