# Generated by Django 6.0.1 on 2026-04-09 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine_record', to='parking.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='parking.parkingslot'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_no', 'status'], name='parking_boo_vehicle_5e4ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['entry_time'], name='parking_boo_entry_t_8ef252_idx'),
        ),
    ]
